//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub color: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::todo_tag::Entity")]
    TodoTag,
}

impl Related<super::todo_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoTag.def()
    }
}

impl Related<super::todo::Entity> for Entity {
    fn to() -> RelationDef {
        super::todo_tag::Relation::Todo.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::todo_tag::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {
    #[sea_orm(entity = "super::todo_tag::Entity")]
    TodoTag,
    #[sea_orm(entity = "super::todo::Entity")]
    Todo,
}
