[package]
name = "remote-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "remote_sync"
path = "src/lib.rs"

[dependencies]
sync-state.workspace = true
sea-orm.workspace = true
chrono.workspace = true
thiserror.workspace = true
tokio = { workspace = true }

[features]
integration = []

[dev-dependencies]
sea-orm = { workspace = true }
tokio = { workspace = true }
migration = { workspace = true }
async-trait = { workspace = true }
pretty_assertions = "1"
