//! SeaORM entities for the todo planner.
//!
//! Generated by sea-orm-codegen, then hand-maintained: enum-typed columns
//! point at [`sea_orm_active_enums`], which is the single source of truth for
//! the domain enums the schema treats as closed. Re-running the entity
//! generator will overwrite these files and revert the enum typing — do not
//! regenerate without re-applying the enum types.

pub mod prelude;

pub mod linear_issue;
pub mod pull_request;
pub mod sync_state;
pub mod tag;
pub mod todo;
pub mod todo_day_plan;
pub mod todo_event;
pub mod todo_linear_issue;
pub mod todo_pull_request;
pub mod todo_tag;

pub mod sea_orm_active_enums;

seaography::register_entity_modules!([
    linear_issue,
    pull_request,
    sync_state,
    tag,
    todo,
    todo_day_plan,
    todo_event,
    todo_linear_issue,
    todo_pull_request,
    todo_tag,
]);

// Bridge each entity Model to Seaography's CustomOutputType so the models can
// appear as GraphQL return types in hand-written mutations and custom outputs.
// Required under the `strict-custom-types` seaography feature. Must live here
// (defining crate) for the orphan rule.
seaography::impl_custom_output_type_for_entity!(todo::Model);
seaography::impl_custom_output_type_for_entity!(tag::Model);
seaography::impl_custom_output_type_for_entity!(todo_tag::Model);
seaography::impl_custom_output_type_for_entity!(todo_day_plan::Model);
seaography::impl_custom_output_type_for_entity!(todo_event::Model);
seaography::impl_custom_output_type_for_entity!(pull_request::Model);
seaography::impl_custom_output_type_for_entity!(todo_pull_request::Model);
seaography::impl_custom_output_type_for_entity!(linear_issue::Model);
seaography::impl_custom_output_type_for_entity!(todo_linear_issue::Model);
seaography::impl_custom_output_type_for_entity!(sync_state::Model);
