//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod linear_issue;
pub mod pull_request;
pub mod sync_state;
pub mod tag;
pub mod todo;
pub mod todo_day_plan;
pub mod todo_event;
pub mod todo_linear_issue;
pub mod todo_pull_request;
pub mod todo_tag;

seaography::register_entity_modules!([
    linear_issue,
    pull_request,
    sync_state,
    tag,
    todo,
    todo_day_plan,
    todo_event,
    todo_linear_issue,
    todo_pull_request,
    todo_tag,
]);
