[package]
name = "sync-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "sync_state"
path = "src/lib.rs"

[dependencies]
sea-orm.workspace = true
seaography.workspace = true
serde.workspace = true
chrono.workspace = true
async-graphql = { workspace = true, features = ["chrono"] }
tokio = { workspace = true }
