[package]
name = "graphql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "graphql"
path = "src/lib.rs"

[dependencies]
todo-domain.workspace = true
github.workspace = true
linear.workspace = true
links.workspace = true
sync-state.workspace = true
sea-orm.workspace = true
seaography.workspace = true
async-graphql = { workspace = true, features = ["chrono", "tokio"] }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
tokio = { workspace = true }
thiserror.workspace = true
